USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS RETAIL_SUPPLY_CHAIN
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Supply Chain Intelligence — Retail/CPG Demo (Snowflake + AWS S3 + Glue/Iceberg + QuickSight)';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.RAW
    DATA_RETENTION_TIME_IN_DAYS = 3
    COMMENT = 'Landing zone: supplier files, POs, demand signals, inventory snapshots';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.CURATED
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Dynamic Tables: inventory health, supplier performance, demand trends';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.AI
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Cortex AI enrichment, Cortex Search, stored procedures';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.ML
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Snowflake ML: demand forecast, inventory anomaly detection';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.LAKE
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Iceberg tables exported to AWS Glue catalog';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.SEARCH
    COMMENT = 'Cortex Search services';

CREATE SCHEMA IF NOT EXISTS RETAIL_SUPPLY_CHAIN.APP
    COMMENT = 'Streamlit application';

CREATE WAREHOUSE IF NOT EXISTS WH_SUPPLY_CHAIN
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Supply Chain Intelligence demo workloads';

GRANT USAGE ON DATABASE RETAIL_SUPPLY_CHAIN TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE RETAIL_SUPPLY_CHAIN TO ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE WH_SUPPLY_CHAIN TO ROLE ACCOUNTADMIN;
