USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_SUPPLY_CHAIN;
USE SCHEMA RAW;
USE WAREHOUSE WH_SUPPLY_CHAIN;

CREATE STAGE IF NOT EXISTS RETAIL_SUPPLY_CHAIN.RAW.SUPPLY_CHAIN_S3_STAGE
    URL = 's3://sg-retail-demos-2026/supply-chain/'
    STORAGE_INTEGRATION = RETAIL_DEMOS_S3_INTEGRATION
    FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE)
    COMMENT = 'External stage for supplier PO files, demand feeds, contract documents';
