USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_SUPPLY_CHAIN;
USE SCHEMA CURATED;
USE WAREHOUSE WH_SUPPLY_CHAIN;

CREATE OR REPLACE DYNAMIC TABLE INVENTORY_HEALTH
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_SUPPLY_CHAIN
AS
SELECT
    i.SNAPSHOT_ID,
    i.PRODUCT_ID,
    p.NAME AS PRODUCT_NAME,
    p.CATEGORY,
    p.SUB_CATEGORY,
    i.WAREHOUSE_ID,
    w.NAME AS WAREHOUSE_NAME,
    w.REGION,
    w.COUNTRY AS WAREHOUSE_COUNTRY,
    i.SNAPSHOT_DATE,
    i.QUANTITY_ON_HAND,
    i.REORDER_POINT,
    i.SAFETY_STOCK,
    i.DAYS_OF_SUPPLY,
    CASE
        WHEN i.QUANTITY_ON_HAND = 0 THEN 'STOCKOUT'
        WHEN i.QUANTITY_ON_HAND < i.SAFETY_STOCK THEN 'CRITICAL'
        WHEN i.QUANTITY_ON_HAND < i.REORDER_POINT THEN 'LOW'
        WHEN i.QUANTITY_ON_HAND > i.REORDER_POINT * 3 THEN 'OVERSTOCK'
        ELSE 'HEALTHY'
    END AS INVENTORY_STATUS,
    CASE
        WHEN i.QUANTITY_ON_HAND = 0 THEN 'CRITICAL'
        WHEN i.QUANTITY_ON_HAND < i.SAFETY_STOCK THEN 'HIGH'
        WHEN i.QUANTITY_ON_HAND < i.REORDER_POINT THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ALERT_SEVERITY,
    p.UNIT_COST,
    p.UNIT_PRICE,
    i.QUANTITY_ON_HAND * p.UNIT_COST AS INVENTORY_VALUE,
    s.NAME AS SUPPLIER_NAME,
    s.COUNTRY AS SUPPLIER_COUNTRY,
    s.RELIABILITY_SCORE AS SUPPLIER_RELIABILITY
FROM RETAIL_SUPPLY_CHAIN.RAW.INVENTORY_SNAPSHOTS i
JOIN RETAIL_SUPPLY_CHAIN.RAW.PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
JOIN RETAIL_SUPPLY_CHAIN.RAW.WAREHOUSES w ON i.WAREHOUSE_ID = w.WAREHOUSE_ID
LEFT JOIN RETAIL_SUPPLY_CHAIN.RAW.SUPPLIERS s ON p.SUPPLIER_ID = s.SUPPLIER_ID
WHERE i.SNAPSHOT_DATE >= DATEADD('day', -30, CURRENT_DATE());

CREATE OR REPLACE DYNAMIC TABLE SUPPLIER_PERFORMANCE
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_SUPPLY_CHAIN
AS
SELECT
    po.SUPPLIER_ID,
    s.NAME AS SUPPLIER_NAME,
    s.COUNTRY,
    s.CITY,
    s.CATEGORY,
    s.RELIABILITY_SCORE,
    s.LEAD_TIME_DAYS AS CONTRACTED_LEAD_TIME,
    COUNT(*) AS TOTAL_POS,
    SUM(CASE WHEN po.STATUS = 'DELIVERED' THEN 1 ELSE 0 END) AS DELIVERED,
    SUM(CASE WHEN po.STATUS = 'DELAYED' THEN 1 ELSE 0 END) AS DELAYED,
    SUM(CASE WHEN po.STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED,
    ROUND(SUM(CASE WHEN po.STATUS = 'DELIVERED' AND po.ACTUAL_DATE <= po.EXPECTED_DATE THEN 1 ELSE 0 END) * 100.0
        / NULLIF(SUM(CASE WHEN po.STATUS = 'DELIVERED' THEN 1 ELSE 0 END), 0), 1) AS ON_TIME_DELIVERY_PCT,
    ROUND(AVG(CASE WHEN po.STATUS = 'DELIVERED' THEN DATEDIFF('day', po.ORDER_DATE, po.ACTUAL_DATE) END), 1) AS AVG_ACTUAL_LEAD_TIME,
    ROUND(SUM(po.TOTAL_COST), 2) AS TOTAL_SPEND,
    SNOWFLAKE.CORTEX.SENTIMENT(
        COALESCE(
            (SELECT LISTAGG(c.CONTRACT_TEXT, ' ') WITHIN GROUP (ORDER BY c.START_DATE DESC)
             FROM RETAIL_SUPPLY_CHAIN.RAW.SUPPLIER_CONTRACTS c
             WHERE c.SUPPLIER_ID = po.SUPPLIER_ID
             LIMIT 1),
            'No contract text available'
        )
    ) AS CONTRACT_SENTIMENT,
    CASE
        WHEN ROUND(SUM(CASE WHEN po.STATUS = 'DELIVERED' AND po.ACTUAL_DATE <= po.EXPECTED_DATE THEN 1 ELSE 0 END) * 100.0
            / NULLIF(SUM(CASE WHEN po.STATUS = 'DELIVERED' THEN 1 ELSE 0 END), 0), 1) >= 90 THEN 'A'
        WHEN ROUND(SUM(CASE WHEN po.STATUS = 'DELIVERED' AND po.ACTUAL_DATE <= po.EXPECTED_DATE THEN 1 ELSE 0 END) * 100.0
            / NULLIF(SUM(CASE WHEN po.STATUS = 'DELIVERED' THEN 1 ELSE 0 END), 0), 1) >= 75 THEN 'B'
        WHEN ROUND(SUM(CASE WHEN po.STATUS = 'DELIVERED' AND po.ACTUAL_DATE <= po.EXPECTED_DATE THEN 1 ELSE 0 END) * 100.0
            / NULLIF(SUM(CASE WHEN po.STATUS = 'DELIVERED' THEN 1 ELSE 0 END), 0), 1) >= 60 THEN 'C'
        ELSE 'D'
    END AS PERFORMANCE_GRADE
FROM RETAIL_SUPPLY_CHAIN.RAW.PURCHASE_ORDERS po
JOIN RETAIL_SUPPLY_CHAIN.RAW.SUPPLIERS s ON po.SUPPLIER_ID = s.SUPPLIER_ID
GROUP BY po.SUPPLIER_ID, s.NAME, s.COUNTRY, s.CITY, s.CATEGORY, s.RELIABILITY_SCORE, s.LEAD_TIME_DAYS;

CREATE OR REPLACE DYNAMIC TABLE DEMAND_TRENDS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_SUPPLY_CHAIN
AS
SELECT
    d.PRODUCT_ID,
    p.NAME AS PRODUCT_NAME,
    p.CATEGORY,
    d.WAREHOUSE_ID,
    w.NAME AS WAREHOUSE_NAME,
    w.REGION,
    d.SIGNAL_DATE,
    d.CHANNEL,
    d.UNITS_SOLD,
    SUM(d.UNITS_SOLD) OVER (PARTITION BY d.PRODUCT_ID, d.WAREHOUSE_ID ORDER BY d.SIGNAL_DATE
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ROLLING_7D_UNITS,
    SUM(d.UNITS_SOLD) OVER (PARTITION BY d.PRODUCT_ID, d.WAREHOUSE_ID ORDER BY d.SIGNAL_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS ROLLING_30D_UNITS,
    AVG(d.UNITS_SOLD) OVER (PARTITION BY d.PRODUCT_ID, d.WAREHOUSE_ID ORDER BY d.SIGNAL_DATE
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AVG_DAILY_7D,
    AVG(d.UNITS_SOLD) OVER (PARTITION BY d.PRODUCT_ID, d.WAREHOUSE_ID ORDER BY d.SIGNAL_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS AVG_DAILY_30D
FROM RETAIL_SUPPLY_CHAIN.RAW.DEMAND_SIGNALS d
JOIN RETAIL_SUPPLY_CHAIN.RAW.PRODUCTS p ON d.PRODUCT_ID = p.PRODUCT_ID
JOIN RETAIL_SUPPLY_CHAIN.RAW.WAREHOUSES w ON d.WAREHOUSE_ID = w.WAREHOUSE_ID
WHERE d.SIGNAL_DATE >= DATEADD('day', -90, CURRENT_DATE());
