USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_SUPPLY_CHAIN;
USE WAREHOUSE WH_SUPPLY_CHAIN;

CREATE OR REPLACE CORTEX SEARCH SERVICE RETAIL_SUPPLY_CHAIN.SEARCH.SUPPLY_CHAIN_SEARCH_SERVICE
    ON CONTRACT_TEXT
    ATTRIBUTES TITLE, SUPPLIER_ID
    WAREHOUSE = WH_SUPPLY_CHAIN
    TARGET_LAG = '1 hour'
AS (
    SELECT
        c.CONTRACT_ID,
        c.SUPPLIER_ID,
        c.TITLE,
        c.CONTRACT_TEXT,
        c.START_DATE,
        c.END_DATE,
        c.ANNUAL_VALUE,
        s.NAME AS SUPPLIER_NAME,
        s.COUNTRY AS SUPPLIER_COUNTRY,
        s.CATEGORY AS SUPPLIER_CATEGORY
    FROM RETAIL_SUPPLY_CHAIN.RAW.SUPPLIER_CONTRACTS c
    LEFT JOIN RETAIL_SUPPLY_CHAIN.RAW.SUPPLIERS s ON c.SUPPLIER_ID = s.SUPPLIER_ID
);
