USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_SUPPLY_CHAIN;
USE SCHEMA ML;
USE WAREHOUSE WH_SUPPLY_CHAIN;

CREATE OR REPLACE VIEW DEMAND_TRAINING_DATA AS
SELECT
    SIGNAL_DATE AS DS,
    SUM(UNITS_SOLD) AS Y,
    PRODUCT_ID
FROM RETAIL_SUPPLY_CHAIN.RAW.DEMAND_SIGNALS
WHERE SIGNAL_DATE >= DATEADD('day', -180, CURRENT_DATE())
GROUP BY SIGNAL_DATE, PRODUCT_ID
ORDER BY PRODUCT_ID, DS;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST DEMAND_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'RETAIL_SUPPLY_CHAIN.ML.DEMAND_TRAINING_DATA'),
    SERIES_COLNAME => 'PRODUCT_ID',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);

CREATE OR REPLACE TABLE DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(DEMAND_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

CREATE OR REPLACE VIEW INVENTORY_TRAIN_OLDER AS
SELECT
    SNAPSHOT_DATE AS DS,
    SUM(QUANTITY_ON_HAND) AS Y,
    WAREHOUSE_ID
FROM RETAIL_SUPPLY_CHAIN.RAW.INVENTORY_SNAPSHOTS
WHERE SNAPSHOT_DATE >= DATEADD('day', -90, CURRENT_DATE())
  AND SNAPSHOT_DATE < DATEADD('day', -7, CURRENT_DATE())
GROUP BY SNAPSHOT_DATE, WAREHOUSE_ID
ORDER BY WAREHOUSE_ID, DS;

CREATE OR REPLACE VIEW INVENTORY_DETECT_DATA AS
SELECT
    SNAPSHOT_DATE AS DS,
    SUM(QUANTITY_ON_HAND) AS Y,
    WAREHOUSE_ID
FROM RETAIL_SUPPLY_CHAIN.RAW.INVENTORY_SNAPSHOTS
WHERE SNAPSHOT_DATE >= DATEADD('day', -7, CURRENT_DATE())
GROUP BY SNAPSHOT_DATE, WAREHOUSE_ID
ORDER BY WAREHOUSE_ID, DS;

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION INVENTORY_ANOMALY_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'RETAIL_SUPPLY_CHAIN.ML.INVENTORY_TRAIN_OLDER'),
    SERIES_COLNAME => 'WAREHOUSE_ID',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y',
    LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE INVENTORY_ANOMALY_RESULTS AS
SELECT * FROM TABLE(INVENTORY_ANOMALY_MODEL!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'RETAIL_SUPPLY_CHAIN.ML.INVENTORY_DETECT_DATA'),
    SERIES_COLNAME => 'WAREHOUSE_ID',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
));
