USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_SUPPLY_CHAIN;
USE SCHEMA LAKE;
USE WAREHOUSE WH_SUPPLY_CHAIN;

CREATE OR REPLACE ICEBERG TABLE DEMAND_FORECAST_ICEBERG
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'SNOWFLAKE'
    BASE_LOCATION = 'demand_forecast/'
(
    PRODUCT_ID STRING,
    FORECAST_DATE TIMESTAMP_NTZ(6),
    FORECAST_UNITS FLOAT,
    LOWER_BOUND FLOAT,
    UPPER_BOUND FLOAT,
    GENERATED_AT TIMESTAMP_NTZ(6)
);

INSERT INTO DEMAND_FORECAST_ICEBERG
SELECT
    f.SERIES::STRING,
    f.TS::TIMESTAMP_NTZ(6),
    f.FORECAST::FLOAT,
    f.LOWER_BOUND::FLOAT,
    f.UPPER_BOUND::FLOAT,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(6)
FROM RETAIL_SUPPLY_CHAIN.ML.DEMAND_FORECAST_RESULTS f;
